### ISSUE TITLE
:bug: fix(bal-footer): sticky footer doesn't stick to bottom

### ISSUE THREAD

**Issue by alexsoeres** [baloise/design-system#1005]
### Current Behavior

The bal-footer no longer appears at the bottom ever since I upgraded my Vue project to the most recent version.

![image](https://github.com/baloise/design-system/assets/45715896/b0bda953-94ab-4e81-9233-5c629f9ddf65)

I also tried creating a new project following the setup guide for vue and got the same issue.

### Expected Behavior

The footer should appear at the bottom, like it used to

### Steps to Reproduce

1. Create blank vue app with design system version 13.6.2
2. Bug appears (tested with chrome and edge)

### Version

13.6.2

### Browsers

Chrome, Microsoft Edge

### Device

Desktop

### Additional Information

I compared between a working version and the current version and some css rules appear to be missing, namely:
```css
/*bal-app*/
.has-sticky-footer {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

/*footer*/
.bal-footer {
  margin-top: auto;
}
```

Adding those rules seemed to do the trick.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
